Add call to input copier
aces/cbrain-plugins-genetics pull request #18
Opened 2024-12-13 15:50 UTC by natacha-beck

This PR go with the following PR in CBRAIN [#1452](https://github.com/aces/cbrain/pull/1452)

2024-12-13 20:08 UTC, MontrealSergiy commented
seems ok, would you like me to test it?

2025-01-17 17:05 UTC, prioux commented on boutiques_descriptors/scrnabox_1.53.01.json
> +            "description": "The working directory where the output files will be saved.",
I don't like that the description says this is an OUTPUT directory even though users select this as an INPUT. There shoudl be a clear explanation that it's both an input and an output

2025-01-17 17:05 UTC, prioux commented on boutiques_descriptors/scrnabox_1.53.01.json
> +            "description": "Output of scRNAbox",
Repeat the explanation that input is also output

2025-01-17 17:07 UTC, prioux requested changes
See comments

2025-01-17 18:02 UTC, merged